name: Pipeline CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 1. Compilación
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      # 2. Pruebas y generación de reporte JaCoCo
      - name: Run tests with maven and generate JaCoCo report
        run: mvn -B test jacoco:report --file pom.xml

      # 3. Publicar artefacto: Reporte de Pruebas Unitarias
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-reports
          path: target/surefire-reports/

      # 4. Publicar artefacto: Reporte de Cobertura JaCoCo
      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/
